### ISSUE TITLE
Traitement des résultats de l'XP

### ISSUE THREAD

**Issue by GDelvoye** [Tatiana-Houssein/XP_staircase#10]
A la fin d'une XP, il faut avoir accès aux données sur :
- les fausses alarmes,
- les omissions
- les détections et rejets corrects.

De plus, afin de tracer une courbe de probabilité de 'bons résultats' en fonction du lag initial du stimulus, il faut rajouter un champ pour logger le stimulus initial.

**Comment by Tatiana-Houssein** [comment]
- [ ] transformation log du streamlight

**Comment by GDelvoye** [comment]
Résultat du front disponibles ici : data/resultats_XX.csv
