### ISSUE TITLE
Ajouter des lags variables

### ISSUE THREAD

**Issue by GDelvoye** [Tatiana-Houssein/XP_staircase#5]
Pour l'instant tous les stimuli ont des lags à 0.

Le but du code est de présenter LE stimulus de lag 0 quand il est présent dans **pool_vus**. Et sinon de présenter un stimulus venant de **pool_non_vus**.

Proposition d'implémentation : 
* chaque stimulus de **pool_non_vus** n'a pas encore de lag associé
* dès qu'un stimulus de **pool_non_vus** passe à la liste **pool_vus**, on lui associe le lag actuel de l'experience (lag_global)
* à chaque fois qu'on propose un nouveau visage à l'utilisateur, on commence par abaisser le lag de tous les stimuli présent dans **pool_vus**
* en fonction de la réponse (correcte ou mauuvaise) de l'utilisateur, le lag_global augmente ou diminiue de 1.

**Comment by Tatiana-Houssein** [comment]
J'ai fait une fonction attrib du lag global si stimulus = non vu 
g ajouté la fonction dans déroulement d'un tour

**Comment by Tatiana-Houssein** [comment]
C bon j'ai crée fonction qui fait qu'à chaque présentation de stim le lag des stim du pool vu baisse de 1 et je l'ai implémenté dans la méthode deroulement_un_tour
